[build]
       command = "curl -fsSL https://raw.githubusercontent.com/flutter/flutter/master/bin/flutter | bash && flutter build web"
       publish = "build/web"
       environment = { FLUTTER_VERSION = "3.24.0" }
