name: Firebase Deploy with Service Account

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Create Firebase Service Account File
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/firebase.json
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

    - name: Firebase Deploy
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase.json
      run: firebase deploy --project=fresh-462110
{
  "type": "service_account",
  "project_id": "fresh-462110",
  "private_key_id": "xxxxxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvg...==\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-abcde@fresh-462110.iam.gserviceaccount.com",
  ...
}
