name: Firebase Deploy with Service Account

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Decode Service Account Key
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase-key.json

    - name: Deploy to Firebase
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json
      run: firebase deploy --project=fresh-462110
